/**
 * Resource Inventory Management
 * This is Swagger UI environment generated for the TMF Resource Inventory Management specification
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * An amount in a given unit
 */
export interface Quantity { 
    /**
     * Numeric value in a given unit
     */
    amount?: number;
    /**
     * Unit
     */
    units?: string;
}
