/**
 * Resource Inventory Management
 * This is Swagger UI environment generated for the TMF Resource Inventory Management specification
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * ResourceOperationalStateType enumerations
 */
export type ResourceOperationalStateType = 'enable' | 'disable';

export const ResourceOperationalStateType = {
    Enable: 'enable' as ResourceOperationalStateType,
    Disable: 'disable' as ResourceOperationalStateType
};
