/**
 * Resource Inventory Management
 * This is Swagger UI environment generated for the TMF Resource Inventory Management specification
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * ResourceStatusType enumerations
 */
export type ResourceStatusType = 'standby' | 'alarm' | 'available' | 'reserved' | 'unknown' | 'suspended';

export const ResourceStatusType = {
    Standby: 'standby' as ResourceStatusType,
    Alarm: 'alarm' as ResourceStatusType,
    Available: 'available' as ResourceStatusType,
    Reserved: 'reserved' as ResourceStatusType,
    Unknown: 'unknown' as ResourceStatusType,
    Suspended: 'suspended' as ResourceStatusType
};
