/**
 * Resource Inventory Management
 * This is Swagger UI environment generated for the TMF Resource Inventory Management specification
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Resource Specification reference: The ResourceSpecification is required to realize a ProductSpecification.
 */
export interface ResourceSpecificationRef { 
    /**
     * Unique identifier of the resource specification
     */
    id: string;
    /**
     * Reference of the resource specification
     */
    href: string;
    /**
     * Name of the requiredResourceSpecification
     */
    name?: string;
    /**
     * Resource specification version
     */
    version?: string;
    /**
     * When sub-classing, this defines the super-class
     */
    baseType?: string;
    /**
     * A URI to a JSON-Schema file that defines additional attributes and relationships
     */
    schemaLocation?: string;
    /**
     * When sub-classing, this defines the sub-class entity name
     */
    type?: string;
    /**
     * The actual type of the target instance when needed for disambiguation.
     */
    referredType?: string;
}
