/**
 * Resource Inventory Management
 * This is Swagger UI environment generated for the TMF Resource Inventory Management specification
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * ResourceAdministrativeStateType enumerations
 */
export type ResourceAdministrativeStateType = 'locked' | 'unlocked' | 'shutdown';

export const ResourceAdministrativeStateType = {
    Locked: 'locked' as ResourceAdministrativeStateType,
    Unlocked: 'unlocked' as ResourceAdministrativeStateType,
    Shutdown: 'shutdown' as ResourceAdministrativeStateType
};
