/**
 * Resource Inventory Management
 * This is Swagger UI environment generated for the TMF Resource Inventory Management specification
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Quantity } from './quantity';
import { TimePeriod } from './timePeriod';

/**
 * An attachment by value or by reference. For AttachmentRefOrValue, the attribute type,schemaLocation and referredType are related to the contained entity and not to AttchmentRefOrValue itself
 */
export interface AttachmentRefOrValue { 
    /**
     * Unique identifier for this particular attachment
     */
    id?: string;
    /**
     * URI for this Attachment
     */
    href?: string;
    /**
     * Attachment type such as video, picture
     */
    attachmentType?: string;
    /**
     * The actual contents of the attachment object, if embedded, encoded as base64
     */
    content?: string;
    /**
     * A narrative text describing the content of the attachment
     */
    description?: string;
    /**
     * Attachment mime type such as extension file for video, picture and document
     */
    mimeType?: string;
    /**
     * The name of the attachment
     */
    name?: string;
    /**
     * Uniform Resource Locator, is a web page address (a subset of URI)
     */
    url?: string;
    /**
     * The size of the attachment.
     */
    size?: Quantity;
    /**
     * The period of time for which the attachment is valid
     */
    validFor?: TimePeriod;
    /**
     * When sub-classing, this defines the super-class
     */
    baseType?: string;
    /**
     * A URI to a JSON-Schema file that defines additional attributes and relationships
     */
    schemaLocation?: string;
    /**
     * When sub-classing, this defines the sub-class entity name
     */
    type?: string;
    /**
     * The actual type of the target instance when needed for disambiguation.
     */
    referredType?: string;
}
