/**
 * API Resource Inventory Management
 * ## TMF API Reference: TMF639 - Resource Inventory   ### Release : 19.5 - December 2019  Resource Inventory  API goal is to provide the ability to manage Resources.  ### Operations Resource Inventory API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity (for administration purposes) - Manage notification of events
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Characteristic } from './characteristic';
// import { ConstraintRef } from './constraintRef';
// import { FeatureRelationship } from './featureRelationship';

/**
 * Configuration feature.
 */
export interface Feature { 
    /**
     * Unique identifier of the feature.
     */
    id?: string;
    /**
     * True if this is a feature group. Default is false.
     */
    // isBundle?: boolean;
    /**
     * True if this feature is enabled. Default is true.
     */
    // isEnabled?: boolean;
    /**
     * This is the name for the feature.
     */
    name: string;
    /**
     * This is a list of feature constraints.
     */
    // constraint?: Array<ConstraintRef>;
    /**
     * This is a list of Characteristics for a particular feature.
     */
    feature_characteristic: Array<Characteristic>;
    // featureRelationship?: Array<FeatureRelationship>;
}