/**
 * Resource Inventory Management
 * This is Swagger UI environment generated for the TMF Resource Inventory Management specification
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Extra information about a given entity
 */
export interface Note { 
    /**
     * Identifier of the note within its containing entity (may or may not be globally unique, depending on provider implementation)
     */
    id?: string;
    /**
     * Author of the note
     */
    author?: string;
    /**
     * Date of the note
     */
    date?: Date;
    /**
     * Text of the note
     */
    text?: string;
    /**
     * When sub-classing, this defines the super-class
     */
    baseType?: string;
    /**
     * A URI to a JSON-Schema file that defines additional attributes and relationships
     */
    schemaLocation?: string;
    /**
     * When sub-classing, this defines the sub-class entity name
     */
    type?: string;
}
