/**
 * Resource Inventory Management
 * This is Swagger UI environment generated for the TMF Resource Inventory Management specification
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * ResourceUsageStateType enumerations
 */
export type ResourceUsageStateType = 'idle' | 'active' | 'busy';

export const ResourceUsageStateType = {
    Idle: 'idle' as ResourceUsageStateType,
    Active: 'active' as ResourceUsageStateType,
    Busy: 'busy' as ResourceUsageStateType
};
