version: '3.9'
services:
  nginx-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - ./src:/src

  docker-json:
    build:
      context: json-server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./json-server:/json-server
      
volumes:
  db_data: {}

